export const weatherData = [
	{
		title: 'Влажность',
		icon: 'humidity',
		value: '75 %',
		minParams: '0%',
		maxParams: '100%',
		range: true,
		humidity: true,
	},
	{
		title: 'Давление',
		icon: 'barometr',
		value: '761',
		value2: 91,
		minParams: '0%',
		maxParams: '1000%',
		param: 'Повышенное',
		pressure: true,
		range: true,
	},
	{
		title: 'Видимость',
		icon: 'visibility',
		value: '28 км',
		minParams: '0%',
		maxParams: '100%',
		param: 'Нормальная',
		range: true,
	},
	{
		title: 'Рассвет',
		icon: 'sunrise',
		value: '8:42',
		param: 'Прошло: ',
		time: '02:47',
	},
	{
		title: 'Закат',
		icon: 'sunset',
		value: '16:37',
		param: 'Осталось: ',
		time: '05:08',
	},
	{
		title: 'Сила ветра',
		icon: 'direction',
		value: '2 м/с',
		param: 'Северо-западный',
	},
];
